# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pyramid_scheme}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Pickett"]
  s.date = %q{2010-02-17}
  s.description = %q{Sphinx index propagtion (currently via the filesystem)}
  s.email = %q{dpickett@enlightsolutions.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/pyramid_scheme.rb",
     "lib/pyramid_scheme/configuration.rb",
     "lib/pyramid_scheme/index_client.rb",
     "lib/pyramid_scheme/index_lock_file.rb",
     "lib/pyramid_scheme/index_provider/file_system.rb",
     "lib/pyramid_scheme/index_server.rb",
     "lib/pyramid_scheme/indexer/base.rb",
     "lib/pyramid_scheme/indexer/thinking_sphinx.rb",
     "lib/pyramid_scheme/indexer/ultrasphinx.rb",
     "lib/pyramid_scheme/required_configuration_not_found.rb",
     "lib/pyramid_scheme/tasks.rb",
     "lib/pyramid_scheme/tasks/rake_tasks.rake",
     "lib/pyramid_scheme/thinking_sphinx_indexer.rb",
     "lib/pyramid_scheme/ultrasphinx_indexer.rb",
     "pyramid_scheme.gemspec",
     "spec/pyramid_scheme.rb",
     "spec/pyramid_scheme/index_client_spec.rb",
     "spec/pyramid_scheme/index_provider/file_system_spec.rb",
     "spec/pyramid_scheme/index_provider_configuration_spec.rb",
     "spec/pyramid_scheme/index_server_spec.rb",
     "spec/pyramid_scheme/indexer/thinking_sphinx_spec.rb",
     "spec/pyramid_scheme/indexer/ultrasphinx_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/pyramid_scheme.rake"
  ]
  s.homepage = %q{http://github.com/dpickett/pyramid_scheme}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Sphinx index propagation}
  s.test_files = [
    "spec/pyramid_scheme/index_client_spec.rb",
     "spec/pyramid_scheme/index_provider/file_system_spec.rb",
     "spec/pyramid_scheme/index_provider_configuration_spec.rb",
     "spec/pyramid_scheme/index_server_spec.rb",
     "spec/pyramid_scheme/indexer/thinking_sphinx_spec.rb",
     "spec/pyramid_scheme/indexer/ultrasphinx_spec.rb",
     "spec/pyramid_scheme.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0.8.7"])
      s.add_runtime_dependency(%q<configatron>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<mocha>, ["= 0.9.8"])
      s.add_development_dependency(%q<fakefs>, ["= 0.2.1"])
    else
      s.add_dependency(%q<rake>, [">= 0.8.7"])
      s.add_dependency(%q<configatron>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<mocha>, ["= 0.9.8"])
      s.add_dependency(%q<fakefs>, ["= 0.2.1"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0.8.7"])
    s.add_dependency(%q<configatron>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<mocha>, ["= 0.9.8"])
    s.add_dependency(%q<fakefs>, ["= 0.2.1"])
  end
end

